# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {D:/An3/SSC/P_35/p_35_ps2 - Copy/p_35_ps2.cache/wt} [current_project]
set_property parent.project_path {D:/An3/SSC/P_35/p_35_ps2 - Copy/p_35_ps2.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo {d:/An3/SSC/P_35/p_35_ps2 - Copy/p_35_ps2.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {D:/An3/SSC/P_35/p_35_ps2 - Copy/p_35_ps2.srcs/sources_1/new/bistabil_D.vhd}
  {D:/An3/SSC/P_35/p_35_ps2 - Copy/p_35_ps2.srcs/sources_1/new/ps2_receiver.vhd}
  {D:/An3/SSC/P_35/p_35_ps2 - Copy/p_35_ps2.srcs/sources_1/new/SSD.vhd}
  {D:/An3/SSC/P_35/p_35_ps2 - Copy/p_35_ps2.srcs/sources_1/new/ps2_transmiter.vhd}
  {D:/An3/SSC/P_35/p_35_ps2 - Copy/p_35_ps2.srcs/sources_1/new/Nexys.vhd}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{D:/An3/SSC/P_35/p_35_ps2 - Copy/p_35_ps2.srcs/constrs_1/imports/p_35_ps2/Nexis4.xdc}}
set_property used_in_implementation false [get_files {{D:/An3/SSC/P_35/p_35_ps2 - Copy/p_35_ps2.srcs/constrs_1/imports/p_35_ps2/Nexis4.xdc}}]


synth_design -top Nexys -part xc7a100tcsg324-1


write_checkpoint -force -noxdef Nexys.dcp

catch { report_utilization -file Nexys_utilization_synth.rpt -pb Nexys_utilization_synth.pb }
